
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int E_Y = 26;
  public static final int ID_ARREGLO = 55;
  public static final int E_X = 25;
  public static final int RES = 9;
  public static final int ENTERO = 51;
  public static final int DOS_PUNTOS = 34;
  public static final int C_CORCHETE = 42;
  public static final int C_LLAVE = 44;
  public static final int A_LLAVE = 43;
  public static final int T_Y = 28;
  public static final int T_X = 27;
  public static final int GraphPie = 20;
  public static final int ARROBA = 46;
  public static final int TITULO = 24;
  public static final int DIV = 11;
  public static final int GUION = 45;
  public static final int CHAR1 = 4;
  public static final int MIN = 18;
  public static final int MAYOR_Q = 39;
  public static final int ID = 54;
  public static final int PUNTO_COMA = 35;
  public static final int GraphBar = 21;
  public static final int MEDIANA = 14;
  public static final int DECIMAL = 52;
  public static final int EOF = 0;
  public static final int MENOR_Q = 40;
  public static final int COMILLA = 47;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int S_IGUAL = 50;
  public static final int COMA = 36;
  public static final int MUL = 10;
  public static final int CADENA = 53;
  public static final int VALUES = 31;
  public static final int MODA = 15;
  public static final int MOD = 12;
  public static final int A_PARENTESIS = 48;
  public static final int PUNTO = 37;
  public static final int C_PARENTESIS = 49;
  public static final int S_EXCLAMACION = 38;
  public static final int VARIANZA = 16;
  public static final int A_CORCHETE = 41;
  public static final int GraphLine = 22;
  public static final int END = 3;
  public static final int SUM = 8;
  public static final int ARR = 7;
  public static final int MEDIA = 13;
  public static final int EXEC = 29;
  public static final int LABEL = 30;
  public static final int DOUBLE1 = 5;
  public static final int MAX = 17;
  public static final int VAR = 6;
  public static final int HISTOGRAM = 23;
  public static final int COLUMNA = 33;
  public static final int PRINT = 32;
  public static final int CONSOLE = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "END",
  "CHAR1",
  "DOUBLE1",
  "VAR",
  "ARR",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "CONSOLE",
  "GraphPie",
  "GraphBar",
  "GraphLine",
  "HISTOGRAM",
  "TITULO",
  "E_X",
  "E_Y",
  "T_X",
  "T_Y",
  "EXEC",
  "LABEL",
  "VALUES",
  "PRINT",
  "COLUMNA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "COMA",
  "PUNTO",
  "S_EXCLAMACION",
  "MAYOR_Q",
  "MENOR_Q",
  "A_CORCHETE",
  "C_CORCHETE",
  "A_LLAVE",
  "C_LLAVE",
  "GUION",
  "ARROBA",
  "COMILLA",
  "A_PARENTESIS",
  "C_PARENTESIS",
  "S_IGUAL",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ID",
  "ID_ARREGLO"
  };
}

